name: freddy

on: [push]

jobs:

  # Job to run pre-checks
  pre-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.0

      - name: Install package
        run: |
          pip install flake8 mypy black isort==4.3.21
      - name: Run pre-checks
        run: |
          flake8 freddy --config=setup.cfg
          flake8 tests --config=setup.cfg
          mypy freddy --ignore-missing-imports
          mypy tests --ignore-missing-imports
          isort -c -rc freddy
          isort -c -rc tests
          black --check --verbose freddy
          black --check --verbose tests

  # Job to run tests
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install the package
        run: |
          pip install -e .[test]

      - name: Run tests
        run: |
          pytest -rfE -s --tb=native -v tests/
